### ISSUE TITLE
Issue with fi_model_generator

### ISSUE THREAD

**Issue by gzyangcs** [lowRISC/synfi#66]
Hello, I have a problem with tool fi_model_generator, when i regenerate example/fault_model.json ,Terminal print info below:

./fi_model_generator.py -j examples/circuit.json -m aes_cipher_control -s 2 -n rnd_ctr -c examples/fault_mapping_cfg.json -o examples/fault_model_test.json
Traceback (most recent call last):
  File "/home/guozhiyang/work/synfi/./fi_model_generator.py", line 442, in <module>
    main()
  File "/home/guozhiyang/work/synfi/./fi_model_generator.py", line 427, in main
    otfi_registers = parse_otfi_registers(otfi_attr, module)
  File "/home/guozhiyang/work/synfi/./fi_model_generator.py", line 263, in parse_otfi_registers
    nets_q[netname]["stage"] = entry["otfi_stage"]
KeyError: 'otfi_stage'

The command used to regenerate .json is copied from fi_model_generator.So what should i do next?

**Comment by nasahlpa** [comment]
Hi,
Could you please try with Python 3.9?
BR

**Comment by rswarbrick** [comment]
I just reproduced this here, and it doesn't seem to be related to the Python version. The code that's dying in `parse_otfi_registers` seems to assume that (by the time it runs) any dict entry with `otfi_type` set to `"register_q"` will also have an field called `otfi_stage`. This isn't true in `circuit.json`: that file has several such entries, but doesn't contain the string "otfi_stage". Should that field have been set by the time `parse_otfi_registers` runs? Or does this script not work with this config file?

**Comment by nasahlpa** [comment]
Hi all,

Sorry for the late reply, I was on vacation. The fi_model_generator is an old artifact and is no longer used & supported in SYNFI. As mentioned in the howto, you need to manually create the FI model. Commit #68 removes this file from the repository.
